language: c
sudo: require
env:
  global:
    - BOOTSTRAP_PANDOC=1

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_github rstudio/rmarkdown
script:
  - make
  - R -e "install.packages(c('reshape2', 'ggplot2', 'plyr', 'psych'))"
