site_name: 'PrincetonR 2016'
#theme: 'readthedocs'
#theme_dir: '.theme_tweak'
repo_url: 'https://github.com/machow/2016-princetonR'
docs_dir: '..'
site_dir: '../site'
pages:
    - Home: 'index.md'
    - Getting Started:
        - 'Rstudio':    '0-getting-started/0a-rstudio.md'
        - 'Rmarkdown':  '0-getting-started/0b-rmarkdown.md'
        - 'R basics': '0-getting-started/0d-rbasics.md'
    - Working with Data:
        - 'Index and summarize': '1-basic-analyses/1a-index-and-summarize.Rmd'
